from collections.abc import Iterator
from typing import Any, Awaitable
import numpy as np
import numpy.typing as npt
from ._types import AnnotationKind, AnnotationSourceKind, AnnotationStatus

class AsrDataError(Exception): ...

class AudioFormat:
    @property
    def encoding(self) -> str: ...
    @property
    def sample_rate(self) -> int: ...
    @property
    def channels(self) -> int: ...

class Waveform:
    def __init__(self, samples: npt.ArrayLike, sample_rate: int, channels: int = 1) -> None: ...
    @property
    def sample_rate(self) -> int: ...
    @property
    def channels(self) -> int: ...
    @property
    def is_normalized(self) -> bool: ...
    @property
    def frame_count(self) -> int: ...
    @property
    def duration_ms(self) -> float: ...
    @property
    def source_format(self) -> AudioFormat | None: ...
    def numpy(self) -> npt.NDArray[np.float32]: ...
    def display(self, autoplay: bool = False) -> None: ...
    def to_mono(self) -> Waveform: ...
    def channel(self, index: int) -> Waveform: ...
    def resample(self, sample_rate: int) -> Waveform: ...
    def normalize(self) -> Waveform: ...
    def slice_ms(self, start_ms: int, end_ms: int) -> Waveform: ...

class Annotation:
    @property
    def id(self) -> str: ...
    @property
    def start_ms(self) -> int: ...
    @property
    def end_ms(self) -> int: ...
    @property
    def status(self) -> AnnotationStatus: ...
    @property
    def kind(self) -> AnnotationKind: ...
    @property
    def text(self) -> str | None: ...
    @property
    def confidence(self) -> float | None: ...
    @property
    def source_kind(self) -> AnnotationSourceKind: ...
    @property
    def source(self) -> str | None: ...
    @property
    def speaker(self) -> str | None: ...
    @property
    def language(self) -> str | None: ...

class Transcript:
    @property
    def text(self) -> str: ...
    @property
    def language(self) -> str | None: ...

class Timeline:
    @property
    def id(self) -> str: ...
    @property
    def audio_id(self) -> str: ...
    @audio_id.setter
    def audio_id(self, value: str) -> None: ...
    @property
    def duration_ms(self) -> int | None: ...
    @duration_ms.setter
    def duration_ms(self, value: int | None) -> None: ...
    @property
    def annotations(self) -> list[Annotation]: ...
    def add_speech(self, start_ms: int, end_ms: int, source: str = "vad", confidence: float | None = None, source_kind: AnnotationSourceKind = "stage") -> Annotation: ...
    def add_silence(self, start_ms: int, end_ms: int, source: str = "vad", confidence: float | None = None, source_kind: AnnotationSourceKind = "stage") -> Annotation: ...
    def add_transcription(self, start_ms: int, end_ms: int, text: str, source: str = "asr", language: str | None = None, confidence: float | None = None, status: AnnotationStatus = "final", source_kind: AnnotationSourceKind = "stage") -> Annotation: ...
    def add_speaker(self, start_ms: int, end_ms: int, speaker: str, source: str = "diarization", confidence: float | None = None, status: AnnotationStatus = "final", source_kind: AnnotationSourceKind = "stage") -> Annotation: ...
    def annotations_by_source(self, source: str, source_kind: AnnotationSourceKind = "model") -> list[Annotation]: ...
    def transcript_by_source(self, source: str, source_kind: AnnotationSourceKind = "model") -> Transcript: ...
    def remove_annotations_by_source(self, source: str, source_kind: AnnotationSourceKind = "model") -> int: ...
    def relabel_annotations_source(self, from_source: str, to_source: str, from_source_kind: AnnotationSourceKind = "stage", to_source_kind: AnnotationSourceKind = "model") -> int: ...
    def transcript(self) -> Transcript: ...

class Audio:
    @staticmethod
    def from_file(path: str, id: str | None = None) -> Audio: ...
    @staticmethod
    def from_url(url: str, id: str | None = None) -> Audio: ...
    @staticmethod
    def from_bytes(data: bytes, id: str | None = None) -> Audio: ...
    @staticmethod
    def from_pcm(data: bytes, sample_rate: int, channels: int = 1, id: str | None = None) -> Audio: ...
    @property
    def id(self) -> str: ...
    @property
    def duration_ms(self) -> int | None: ...
    @duration_ms.setter
    def duration_ms(self, value: int | None) -> None: ...
    def timeline(self, channel: str | int) -> Timeline | None: ...
    def ensure_timeline(self, channel: str | int) -> Timeline: ...
    def remove_timeline(self, channel: str | int) -> bool: ...
    @property
    def timelines(self) -> dict[str, Timeline]: ...
    @property
    def metadata(self) -> dict[str, Any]: ...
    def load(self) -> Waveform: ...
    def aload(self) -> Awaitable[Waveform]: ...
    def validate(self) -> None: ...

class AudioDB:
    def __init__(self, path: str, read_only: bool = False) -> None: ...
    def insert(self, audio: Audio) -> None: ...
    def query(self, limit: int = 100, *, after: str | None = None, min_duration_ms: int | None = None, max_duration_ms: int | None = None, metadata: dict[str, Any] | None = None) -> list[Audio]: ...
    def update(self, audio: Audio) -> bool: ...
    def update_many(self, audios: list[Audio]) -> int: ...
    def delete(self, audio_id: str) -> bool: ...
    @property
    def metadata(self) -> dict[str, Any]: ...
    def set_metadata(self, key: str, value: Any) -> None: ...
    def metadata_value(self, key: str) -> Any | None: ...
    def delete_metadata(self, key: str) -> bool: ...
    def __getitem__(self, audio_id: str) -> Audio: ...
    def __contains__(self, audio_id: str) -> bool: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[Audio]: ...
