from collections.abc import AsyncIterator, Iterator
from typing import Any, Awaitable, Literal
import numpy as np
import numpy.typing as npt
from ._types import AnnotationKind

class AsrDataError(Exception): ...

def normalize_zh(text: str) -> str: ...

class AudioFormat:
    @property
    def encoding(self) -> str: ...
    @property
    def sample_rate(self) -> int: ...
    @property
    def channels(self) -> int: ...

class _AudioLoadTask:
    def done(self) -> bool: ...
    def result(self) -> Audio: ...

class AudioSource:
    @staticmethod
    def from_path(path: str) -> AudioSource: ...
    @staticmethod
    def from_url(url: str) -> AudioSource: ...
    @staticmethod
    def from_bytes(data: bytes) -> AudioSource: ...
    @staticmethod
    def from_base64(data: str) -> AudioSource: ...
    @staticmethod
    def from_pcm(
        data: bytes, sample_rate: int, channels: int = 1
    ) -> AudioSource: ...
    @property
    def kind(self) -> Literal["path", "url", "bytes", "base64", "pcm"]: ...
    @property
    def path(self) -> str | None: ...
    @property
    def url(self) -> str | None: ...
    @property
    def bytes(self) -> bytes | None: ...
    @property
    def base64(self) -> str | None: ...
    @property
    def pcm(self) -> bytes | None: ...
    @property
    def sample_rate(self) -> int | None: ...
    @property
    def channels(self) -> int | None: ...
    def load(
        self, *, sample_rate: int | None = None, mono: bool | None = None
    ) -> Audio: ...
    def stream(
        self,
        chunk_size_ms: int = 100,
        *,
        sample_rate: int | None = None,
        mono: bool | None = None,
    ) -> Iterator[AudioChunk]: ...
    def aload(
        self, *, sample_rate: int | None = None, mono: bool | None = None
    ) -> Awaitable[Audio]: ...
    def astream(
        self,
        chunk_size_ms: int = 100,
        *,
        sample_rate: int | None = None,
        mono: bool | None = None,
    ) -> AsyncIterator[AudioChunk]: ...

class Audio:
    def __init__(
        self, samples: npt.ArrayLike, sample_rate: int, channels: int = 1
    ) -> None: ...
    @staticmethod
    def from_path(path: str) -> Audio: ...
    @staticmethod
    def from_url(url: str) -> Audio: ...
    @staticmethod
    def from_bytes(data: bytes) -> Audio: ...
    @staticmethod
    def from_base64(data: str) -> Audio: ...
    @staticmethod
    def from_pcm(data: bytes, sample_rate: int, channels: int = 1) -> Audio: ...
    @staticmethod
    def from_source(
        source: AudioSource,
    ) -> Audio: ...
    @staticmethod
    def _start_aload_from_path(path: str) -> _AudioLoadTask: ...
    @staticmethod
    def _start_aload_from_source(
        source: AudioSource,
    ) -> _AudioLoadTask: ...
    @property
    def sample_rate(self) -> int: ...
    @property
    def channels(self) -> int: ...
    @property
    def frame_count(self) -> int: ...
    @property
    def duration_ms(self) -> float: ...
    @property
    def source_format(self) -> AudioFormat | None: ...
    @property
    def samples(self) -> npt.NDArray[np.float32]: ...
    def display(
        self,
        start_ms: int | None = None,
        end_ms: int | None = None,
        autoplay: bool = False,
    ) -> None: ...
    def to_mono(self) -> Audio: ...
    def channel(self, index: int) -> Audio: ...
    def resample(self, sample_rate: int) -> Audio: ...
    def slice_ms(self, start_ms: int, end_ms: int) -> Audio: ...
    def split_at_low_energy(self, max_duration_ms: int) -> list[Audio]: ...

class AudioChunk:
    @property
    def sample_rate(self) -> int: ...
    @property
    def channels(self) -> int: ...
    @property
    def offset_ms(self) -> int: ...
    @property
    def is_final(self) -> bool: ...
    @property
    def frame_count(self) -> int: ...
    @property
    def duration_ms(self) -> float: ...
    @property
    def source_format(self) -> AudioFormat | None: ...
    @property
    def samples(self) -> npt.NDArray[np.float32]: ...
    def to_mono(self) -> AudioChunk: ...
    def channel(self, index: int) -> AudioChunk: ...
    def resample(self, sample_rate: int) -> AudioChunk: ...
    def slice_ms(self, start_ms: int, end_ms: int) -> AudioChunk: ...

class Token:
    def __init__(
        self,
        text: str,
        *,
        start_ms: int | None = None,
        end_ms: int | None = None,
        confidence: float | None = None,
    ) -> None: ...
    @property
    def text(self) -> str: ...
    @property
    def start_ms(self) -> int | None: ...
    @property
    def end_ms(self) -> int | None: ...
    @property
    def confidence(self) -> float | None: ...

class Transcription:
    def __init__(
        self,
        text: str,
        *,
        tokens: list[Token] | None = None,
        language: str | None = None,
        confidence: float | None = None,
    ) -> None: ...
    @property
    def text(self) -> str: ...
    @property
    def tokens(self) -> list[Token]: ...
    @property
    def language(self) -> str | None: ...
    @property
    def confidence(self) -> float | None: ...

class Speaker:
    def __init__(
        self,
        name: str,
        *,
        transcription: Transcription | None = None,
    ) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def transcription(self) -> Transcription | None: ...

class Annotation:
    @property
    def id(self) -> str: ...
    @property
    def start_ms(self) -> int: ...
    @property
    def end_ms(self) -> int: ...
    def kind(self) -> AnnotationKind: ...
    @property
    def confidence(self) -> float | None: ...
    @property
    def source(self) -> str | None: ...
    @property
    def payload(self) -> Token | Transcription | Speaker | dict[str, Any] | None: ...
    @payload.setter
    def payload(self, value: Token | Transcription | Speaker | None) -> None: ...

class Transcript:
    @property
    def text(self) -> str: ...
    @property
    def language(self) -> str | None: ...

class TranscriptionEvaluation:
    @property
    def source(self) -> str: ...
    @property
    def reference(self) -> str: ...
    @property
    def hypothesis(self) -> str: ...
    @property
    def normalized_reference(self) -> str: ...
    @property
    def normalized_hypothesis(self) -> str: ...
    @property
    def normalization(self) -> Literal["none", "zh_tn"]: ...
    @property
    def matches(self) -> int: ...
    @property
    def substitutions(self) -> int: ...
    @property
    def deletions(self) -> int: ...
    @property
    def insertions(self) -> int: ...
    @property
    def reference_chars(self) -> int: ...
    @property
    def hypothesis_chars(self) -> int: ...
    @property
    def cer(self) -> float: ...
    @property
    def precision(self) -> float: ...
    @property
    def recall(self) -> float: ...
    @property
    def f1(self) -> float: ...
    @property
    def exact_match(self) -> bool: ...

class SpeechEvaluation:
    @property
    def source(self) -> str: ...
    @property
    def reference_ms(self) -> int: ...
    @property
    def predicted_ms(self) -> int: ...
    @property
    def true_positive_ms(self) -> int: ...
    @property
    def true_negative_ms(self) -> int: ...
    @property
    def false_positive_ms(self) -> int: ...
    @property
    def false_negative_ms(self) -> int: ...
    @property
    def precision(self) -> float: ...
    @property
    def recall(self) -> float: ...
    @property
    def f1(self) -> float: ...
    @property
    def iou(self) -> float: ...

class TimelineEvaluation:
    @property
    def transcription(self) -> TranscriptionEvaluation | None: ...
    @property
    def speech(self) -> SpeechEvaluation | None: ...

class ReferenceAnnotations:
    @property
    def annotations(self) -> list[Annotation]: ...
    def add_speech(
        self,
        start_ms: int,
        end_ms: int,
        confidence: float | None = None,
    ) -> Annotation: ...
    def add_transcription(
        self,
        start_ms: int,
        end_ms: int,
        transcription: Transcription,
        confidence: float | None = None,
    ) -> Annotation: ...
    def add_speaker(
        self,
        start_ms: int,
        end_ms: int,
        speaker: Speaker,
        confidence: float | None = None,
    ) -> Annotation: ...
    def transcript(self) -> Transcript: ...
    def __len__(self) -> int: ...

class PredictionAnnotations:
    @property
    def annotations(self) -> list[Annotation]: ...
    @property
    def sources(self) -> list[str]: ...
    def add_speech(
        self,
        start_ms: int,
        end_ms: int,
        *,
        source: str,
        confidence: float | None = None,
    ) -> Annotation: ...
    def add_transcription(
        self,
        start_ms: int,
        end_ms: int,
        transcription: Transcription,
        *,
        source: str,
        confidence: float | None = None,
    ) -> Annotation: ...
    def add_speaker(
        self,
        start_ms: int,
        end_ms: int,
        speaker: Speaker,
        *,
        source: str,
        confidence: float | None = None,
    ) -> Annotation: ...
    def by_source(self, source: str) -> list[Annotation]: ...
    def transcript(self, source: str) -> Transcript: ...
    def remove_by_source(self, source: str) -> int: ...
    def relabel_source(self, from_source: str, to_source: str) -> int: ...
    def __len__(self) -> int: ...

class Timeline:
    @property
    def id(self) -> str: ...
    @property
    def audio_id(self) -> str: ...
    @audio_id.setter
    def audio_id(self, value: str) -> None: ...
    @property
    def duration_ms(self) -> int: ...
    @property
    def reference(self) -> ReferenceAnnotations: ...
    @property
    def prediction(self) -> PredictionAnnotations: ...
    def eval(
        self,
        *,
        transcription: str | None = None,
        speech: str | None = None,
        normalize: bool = True,
    ) -> TimelineEvaluation: ...

class AudioDoc:
    def __init__(
        self,
        source: AudioSource,
        id: str | None = None,
    ) -> None: ...
    @property
    def id(self) -> str: ...
    @property
    def source(self) -> AudioSource: ...
    def timeline(self, channel: str | int) -> Timeline | None: ...
    def ensure_timeline(
        self, channel: str | int, duration_ms: int | float | None = None
    ) -> Timeline: ...
    def remove_timeline(self, channel: str | int) -> bool: ...
    @property
    def timelines(self) -> dict[str, Timeline]: ...
    @property
    def metadata(self) -> dict[str, Any]: ...
    def validate(self) -> None: ...

class AudioDB:
    def __init__(self, path: str, read_only: bool = False) -> None: ...
    def insert(self, audio: AudioDoc) -> None: ...
    def query(
        self,
        limit: int = 100,
        *,
        after: str | None = None,
        min_duration_ms: int | None = None,
        max_duration_ms: int | None = None,
        metadata: dict[str, Any] | None = None,
    ) -> list[AudioDoc]: ...
    def update(self, audio: AudioDoc) -> bool: ...
    def update_many(self, audios: list[AudioDoc]) -> int: ...
    def delete(self, audio_id: str) -> bool: ...
    @property
    def metadata(self) -> dict[str, Any]: ...
    def set_metadata(self, key: str, value: Any) -> None: ...
    def metadata_value(self, key: str) -> Any | None: ...
    def delete_metadata(self, key: str) -> bool: ...
    def __getitem__(self, audio_id: str) -> AudioDoc: ...
    def __contains__(self, audio_id: str) -> bool: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[AudioDoc]: ...
