from collections.abc import AsyncIterator, Iterator
from typing import Any, Awaitable, Literal
import numpy as np
import numpy.typing as npt
from ._types import AnnotationKind, AnnotationSourceKind, AnnotationStatus

class AsrDataError(Exception): ...

class AudioFormat:
    @property
    def encoding(self) -> str: ...
    @property
    def sample_rate(self) -> int: ...
    @property
    def channels(self) -> int: ...

class _AudioLoadTask:
    def done(self) -> bool: ...
    def result(self) -> Audio: ...

class AudioSource:
    @staticmethod
    def from_path(path: str) -> AudioSource: ...
    @staticmethod
    def from_url(url: str) -> AudioSource: ...
    @staticmethod
    def from_bytes(data: bytes) -> AudioSource: ...
    @staticmethod
    def from_base64(data: str) -> AudioSource: ...
    @staticmethod
    def from_pcm(
        data: bytes, sample_rate: int, channels: int = 1
    ) -> AudioSource: ...
    @property
    def kind(self) -> Literal["path", "url", "bytes", "base64", "pcm"]: ...
    @property
    def path(self) -> str | None: ...
    @property
    def url(self) -> str | None: ...
    @property
    def bytes(self) -> bytes | None: ...
    @property
    def base64(self) -> str | None: ...
    @property
    def pcm(self) -> bytes | None: ...
    @property
    def sample_rate(self) -> int | None: ...
    @property
    def channels(self) -> int | None: ...
    def load(
        self, *, sample_rate: int | None = None, mono: bool | None = None
    ) -> Audio: ...
    def stream(
        self,
        chunk_size_ms: int = 100,
        *,
        sample_rate: int | None = None,
        mono: bool | None = None,
    ) -> Iterator[AudioChunk]: ...
    def aload(
        self, *, sample_rate: int | None = None, mono: bool | None = None
    ) -> Awaitable[Audio]: ...
    def astream(
        self,
        chunk_size_ms: int = 100,
        *,
        sample_rate: int | None = None,
        mono: bool | None = None,
    ) -> AsyncIterator[AudioChunk]: ...

class Audio:
    def __init__(
        self, samples: npt.ArrayLike, sample_rate: int, channels: int = 1
    ) -> None: ...
    @staticmethod
    def from_path(path: str) -> Audio: ...
    @staticmethod
    def from_url(url: str) -> Audio: ...
    @staticmethod
    def from_bytes(data: bytes) -> Audio: ...
    @staticmethod
    def from_base64(data: str) -> Audio: ...
    @staticmethod
    def from_pcm(data: bytes, sample_rate: int, channels: int = 1) -> Audio: ...
    @staticmethod
    def from_source(
        source: AudioSource,
    ) -> Audio: ...
    @staticmethod
    def _start_aload_from_path(path: str) -> _AudioLoadTask: ...
    @staticmethod
    def _start_aload_from_source(
        source: AudioSource,
    ) -> _AudioLoadTask: ...
    @property
    def sample_rate(self) -> int: ...
    @property
    def channels(self) -> int: ...
    @property
    def frame_count(self) -> int: ...
    @property
    def duration_ms(self) -> float: ...
    @property
    def source_format(self) -> AudioFormat | None: ...
    @property
    def samples(self) -> npt.NDArray[np.float32]: ...
    def display(
        self,
        start_ms: int | None = None,
        end_ms: int | None = None,
        autoplay: bool = False,
    ) -> None: ...
    def to_mono(self) -> Audio: ...
    def channel(self, index: int) -> Audio: ...
    def resample(self, sample_rate: int) -> Audio: ...
    def slice_ms(self, start_ms: int, end_ms: int) -> Audio: ...
    def split_at_low_energy(self, max_duration_ms: int) -> list[Audio]: ...

class AudioChunk:
    @property
    def sample_rate(self) -> int: ...
    @property
    def channels(self) -> int: ...
    @property
    def offset_ms(self) -> int: ...
    @property
    def is_final(self) -> bool: ...
    @property
    def frame_count(self) -> int: ...
    @property
    def duration_ms(self) -> float: ...
    @property
    def source_format(self) -> AudioFormat | None: ...
    @property
    def samples(self) -> npt.NDArray[np.float32]: ...
    def to_mono(self) -> AudioChunk: ...
    def channel(self, index: int) -> AudioChunk: ...
    def resample(self, sample_rate: int) -> AudioChunk: ...
    def slice_ms(self, start_ms: int, end_ms: int) -> AudioChunk: ...

class Annotation:
    @property
    def id(self) -> str: ...
    @property
    def start_ms(self) -> int: ...
    @property
    def end_ms(self) -> int: ...
    @property
    def status(self) -> AnnotationStatus: ...
    @property
    def kind(self) -> AnnotationKind: ...
    @property
    def text(self) -> str | None: ...
    @property
    def confidence(self) -> float | None: ...
    @property
    def source_kind(self) -> AnnotationSourceKind: ...
    @property
    def source(self) -> str | None: ...
    @property
    def speaker(self) -> str | None: ...
    @property
    def language(self) -> str | None: ...

class Transcript:
    @property
    def text(self) -> str: ...
    @property
    def language(self) -> str | None: ...

class Timeline:
    @property
    def id(self) -> str: ...
    @property
    def audio_id(self) -> str: ...
    @audio_id.setter
    def audio_id(self, value: str) -> None: ...
    @property
    def duration_ms(self) -> int: ...
    @property
    def annotations(self) -> list[Annotation]: ...
    def add_speech(
        self,
        start_ms: int,
        end_ms: int,
        source: str = "vad",
        confidence: float | None = None,
        source_kind: AnnotationSourceKind = "stage",
    ) -> Annotation: ...
    def add_silence(
        self,
        start_ms: int,
        end_ms: int,
        source: str = "vad",
        confidence: float | None = None,
        source_kind: AnnotationSourceKind = "stage",
    ) -> Annotation: ...
    def add_transcription(
        self,
        start_ms: int,
        end_ms: int,
        text: str,
        source: str = "asr",
        language: str | None = None,
        confidence: float | None = None,
        status: AnnotationStatus = "final",
        source_kind: AnnotationSourceKind = "stage",
    ) -> Annotation: ...
    def add_speaker(
        self,
        start_ms: int,
        end_ms: int,
        speaker: str,
        source: str = "diarization",
        confidence: float | None = None,
        status: AnnotationStatus = "final",
        source_kind: AnnotationSourceKind = "stage",
    ) -> Annotation: ...
    def annotations_by_source(
        self, source: str, source_kind: AnnotationSourceKind = "model"
    ) -> list[Annotation]: ...
    def transcript_by_source(
        self, source: str, source_kind: AnnotationSourceKind = "model"
    ) -> Transcript: ...
    def remove_annotations_by_source(
        self, source: str, source_kind: AnnotationSourceKind = "model"
    ) -> int: ...
    def relabel_annotations_source(
        self,
        from_source: str,
        to_source: str,
        from_source_kind: AnnotationSourceKind = "stage",
        to_source_kind: AnnotationSourceKind = "model",
    ) -> int: ...
    def transcript(self) -> Transcript: ...

class AudioDoc:
    def __init__(
        self,
        source: AudioSource,
        id: str | None = None,
    ) -> None: ...
    @property
    def id(self) -> str: ...
    @property
    def source(self) -> AudioSource: ...
    def timeline(self, channel: str | int) -> Timeline | None: ...
    def ensure_timeline(
        self, channel: str | int, duration_ms: int | None = None
    ) -> Timeline: ...
    def remove_timeline(self, channel: str | int) -> bool: ...
    @property
    def timelines(self) -> dict[str, Timeline]: ...
    @property
    def metadata(self) -> dict[str, Any]: ...
    def validate(self) -> None: ...

class AudioDB:
    def __init__(self, path: str, read_only: bool = False) -> None: ...
    def insert(self, audio: AudioDoc) -> None: ...
    def query(
        self,
        limit: int = 100,
        *,
        after: str | None = None,
        min_duration_ms: int | None = None,
        max_duration_ms: int | None = None,
        metadata: dict[str, Any] | None = None,
    ) -> list[AudioDoc]: ...
    def update(self, audio: AudioDoc) -> bool: ...
    def update_many(self, audios: list[AudioDoc]) -> int: ...
    def delete(self, audio_id: str) -> bool: ...
    @property
    def metadata(self) -> dict[str, Any]: ...
    def set_metadata(self, key: str, value: Any) -> None: ...
    def metadata_value(self, key: str) -> Any | None: ...
    def delete_metadata(self, key: str) -> bool: ...
    def __getitem__(self, audio_id: str) -> AudioDoc: ...
    def __contains__(self, audio_id: str) -> bool: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[AudioDoc]: ...
